### ISSUE TITLE
Lossy WEBP with alpha: source slice length (761600) does not match destination slice length (997920)

### ISSUE THREAD

**Issue by IonImpulse** [image-rs/image#1856]
Whenever I try to decode [this webp image](https://make.hmc.edu/img/equipment/cricut.webp) I get the following error:
```
panicked at 'source slice length (761600) does not match destination slice length (997920)'
C:\Users\Ethan Vazquez\.cargo\registry\src\github.com-1ecc6299db9ec823\image-0.24.5\./src\codecs\webp\extended.rs:459:21
```
![image](https://user-images.githubusercontent.com/24578597/217739486-e72e0ca6-ba6b-4ce1-81c3-6b275bd30968.png)

**Comment by IonImpulse** [comment]
Ok after further investigation it seems like it's cropping to opaque, which makes the dimensions shrink from 594x420 to 544x350. The buffer is created with the total bytes of the image, so 594 * 420 * 4 (for RGBA), which equals 997920. But the image slice is cut down to 544 * 350 * 4 = 761600. I'll try to open a pull request soonish.
![image](https://user-images.githubusercontent.com/24578597/218228845-0284c96e-a15f-4d18-a8e6-3fb47dfcf78b.png)

**Comment by mikedilger** [comment]
I get this same bug 3 lines down at 462.

**Comment by bu5hm4nn** [comment]
> I get this same bug 3 lines down at 462.
I just extracted the bug @mikedilger is describing into a project for reproduction (still present in 0.24.5):
https://github.com/bu5hm4nn/imagers-webp-crash

**Comment by Shnatsel** [comment]
I'm seeing a bunch of these panics in the 7500 images I've scraped off the web, as of commit 55732d14434cf639f2e79890f43a1d48bfb8617b

I didn't spend time filtering these out since you already have a reproducing test case, but you can find the full corpus [here](https://mega.nz/file/1pkiWKIb#O67dKU6Pj5dxDzKwtjEe6Nn7fu6ScxHgAd1CqypoYuI) if you wish.

**Comment by qarmin** [comment]
96 byte files which cause crash - [Broken.zip](https://github.com/image-rs/image/files/11409310/Broken.zip)

**Comment by bu5hm4nn** [comment]
I just set out to finally fix this bug and found that it is already fixed in 0.24.6.

The problem is that https://github.com/emilk/egui/ 's Lockfile is stuck at 0.24.5 so you are not getting the benefits.

I asked them to upgrade: https://github.com/emilk/egui/issues/2973

Specifying `image = "0.24.6"` in my reproducing example did work however to pull in the newer version.

@Shnatsel can you verify on your large set of files?

**Comment by Shnatsel** [comment]
It still happens on latest commit cddf30f5f823540e068d1cf7555c1aec20f1e716, released after 0.24.6 shipped.

```
thread 'main' panicked at 'source slice length (41612) does not match destination slice length (65536)', image/./src/codecs/webp/extended.rs:472:21
```

Three sample files triggering the error: [webp_slice_length_mismatch.zip](https://github.com/image-rs/image/files/11412123/webp_slice_length_mismatch.zip)

**Comment by bu5hm4nn** [comment]
@Shnatsel not sure if you are in a position to try my branch. It did work for all 3 images in your zip.

This bug is specific to webp animations that have things moving over a transparent background, which will result in individual frames being smaller than the canvas. Code was just copying the first frame but as stated, it can be smaller. The code for actually rendering the frames was already there, but not used.
